### ISSUE TITLE
Documentation doesn't specify permissions needed for database command

### ISSUE THREAD

**Issue by Imar** [dynamicweb/CLI#11]
The docs at https://github.com/dynamicweb/CLI describe the database command but don't explain the necessary permissions. I have a solution running with a SQL Server connection in integrated mode and when I execute the following command, I get an error:

dw database -e "D:\Backups\"

The error is: Failed download, check users database permissions

Which permissions are needed to make this work?

**Comment by frederik5480** [comment]
We had a bug with the Management API not allowing commands without properties to be used, this will be fixed in the upcoming version, and the CLI seeing an error led it to believe there was permissions missing.
The permissions necessary for this however is the 'view any definition', this would be found in the Server Properties -> Permissions -> Your user -> View any definition
This will be detailed in the readme as well.
